apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  local:
    path: /volumes/pv01
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kiamol
          operator: In
          values:
          - ch05
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

