apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    kiamol: ch12-lab
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          # TODO - add resource limits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web-test
  namespace: pi-test
  labels:
    kiamol: ch12-lab
spec:
  replicas: 8
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      namespace: pi-test
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 62m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web-dev
  namespace: pi-dev
  labels:
    kiamol: ch12-lab
spec:
  replicas: 8
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
      namespace: pi-dev
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 62m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web-uat
  namespace: pi-uat
  labels:
    kiamol: ch12-lab
spec:
  replicas: 8
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      namespace: pi-uat
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: web
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 187m

