apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    pod: pod-a
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: pod
              operator: In
              values:
              - pod-b
          topologyKey: kubernetes.io/hostname 
        
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: security
    #           operator: In
    #           values:
    #           - S2
    #       topologyKey: kubernetes.io/hostname 
  containers:
  - name: with-pod-affinity
    image: k8s.gcr.io/pause:2.0
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    pod: pod-b
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: pod
            operator: In
            values:
            - pod-a
        topologyKey: kubernetes.io/hostname 
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: security
    #           operator: In
    #           values:
    #           - S2
    #       topologyKey: kubernetes.io/hostname 
  containers:
  - name: with-pod-affinity
    image: k8s.gcr.io/pause:2.0