apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: my-kps
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: my-kps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 17.0.2
    chart: kube-prometheus-stack-17.0.2
    heritage: Helm
    release: my-kps
    self-monitor: "true"
  name: my-kps-kube-prometheus-sta-prometheus-nodeport
  namespace: monitoring

spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: my-kps-kube-prometheus-sta-prometheus
  type: NodePort
