apiVersion: v1
kind: Service
metadata:
  name: vweb
  labels:
    kiamol: ch09-lab
spec:
  ports:
    - port: 8090
      targetPort: http
  selector:
    app: vweb
    version: v2
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vweb-v1
  labels:
    kiamol: ch09-lab
spec:
  ports:
    - port: 8091
      targetPort: http
  selector:
    app: vweb
    version: v1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: vweb-v2
  labels:
    kiamol: ch09-lab
spec:
  ports:
    - port: 8092
      targetPort: http
  selector:
    app: vweb
    version: v2
  type: LoadBalancer