apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: timechecks.ch20.kiamol.net
spec:
  group: ch20.kiamol.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                environment:
                  type: string
                interval:
                  type: integer
      additionalPrinterColumns:
      - name: environment
        type: string
        description: Environment
        jsonPath: .spec.environment
      - name: interval
        type: integer
        description: Interval
        jsonPath: .spec.interval
  scope: Namespaced
  names:
    plural: timechecks
    singular: timecheck
    kind: TimeCheck
    shortNames:
    - tc
    - tcs
