apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-tools-admin
  namespace: default
  labels:
    kiamol: ch17
subjects:
- kind: ServiceAccount
  name: rbac-tools
  namespace: default
roleRef:
  kind: ClusterRole
  name: rbac-reader   # think *very* carefully before you do this!
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-reader
  labels: 
    kiamol: ch17
rules:
- apiGroups: ["rbac.authorization.k8s.io"] 
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rbac-reader-default
  namespace: default 
  labels:
    kiamol: ch17
rules:
- apiGroups: ["rbac.authorization.k8s.io"] 
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rbac-reader-default
  namespace: default 
  labels:
    kiamol: ch17
subjects:
- kind: ServiceAccount
  name: rbac-tools
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rbac-reader-default