apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  labels:
    kiamol: ch07-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      initContainers:
        - name: init-config
          image: kiamol/ch03-sleep
          command: ["sh", "-c", "echo '#!/bin/sh\n\n/usr/bin/dotnet Pi.Web.dll -m web' > /init/startup.sh && chmod +x /init/startup.sh"]          
          volumeMounts:
            - name: init-dir
              mountPath: /init
      containers:
        - image: kiamol/ch05-pi
          # command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          command: ["/init/startup.sh"]
          name: web
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: init-dir
              mountPath: /init
        - name: version
          image: kiamol/ch03-sleep  
          command: ['sh', '-c', "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: application/json\nContent-Length: 18\n\n{\"version\": \"0.1\"}' | nc -l -p 8080; done"]
          ports:
            - containerPort: 8080
              name: http

      volumes:
        - name: init-dir
          emptyDir: {}
